### ISSUE TITLE
Custom model training

### ISSUE THREAD

**Issue by enjoykcc456** [IBMSystemsCenterMontpellier/visual-insights-custom-models#2]
Hi,

I have tested out the custom model with the monkey dataset in IBM Visual Insights. It is able to train and deploy properly. 

But, when i wanted to train with my own dataset with 190+ classes. The training progress bar only show "Scheduling..", then after awhile, it shows completed without showing any training progression (with graph etc.) like usual. The trained model give no accuracy details in 'Model Details' and also cant be deployed.

May i know is there any places that i did wrong causing it not to work?

Thanks

**Comment by MaximeDeloche** [comment]
Hi @enjoykcc456 , sorry for the late reply; I missed the notification.
That's weird. 2 questions I have:

1. Did you use the scripts in the `tests/` directory to test your code outside IVI, does it run successfully?
2. Have you managed to check the logs of the container? If you installed IVI standalone, launch your training and run `sudo docker ps` on the machine: you should find the name of your training container (the most recent that containts "train" in its name), run `sudo docker logs -f YOUR_CONTAINER_HASH` and post the logs here.

Hope it helps

**Comment by enjoykcc456** [comment]
Hi @MaximeDeloche ,

No problem at all. Thanks a lot for the reply.

I tested the data set with the scripts in the `tests/` directory. The following error occurs:
`ValueError: could not broadcast input array from shape (224,224,3) into shape (224,224)`
I think there are grey-scale some images in the data set that causes this error. Hence, i changed the following line of code in the `train.py`.
From:
`return np.array(Image.open(path).resize(self.img_size))`
To:
`return np.array(Image.open(path).convert('RGB').resize(self.img_size))`

And now i am able to train the data set with the custom model. Kindly let me know if this is the correct fix for the problem.

Some questions:
1) May i know what is the tensorflow version currently being used for IVI? 
So, that i can set up the same version of tensorflow when doing the testing with the scripts in `tests/` directory.

2) For the training of image classification model in IVI, there is GoogleNet with transfer learning available. Would like to know in which of the following way is actually the transfer learning being done underneath:
a) Full tune the entire network with initialized weights from a pre-trained model (Unfreeze all layers in imagenet pre-trained conv base and classifier/fully-connected layers added on top for custom classes)
b) Freeze all the layers in the pre-trained conv base and train only the fully-connected layers added on top.
c) Unfreeze some layers in the pre-trained conv base and train together with the fully-connected layers added on top.

3) When i try to pre-process the training images with respective network arch's preprocess_input       function (e.g. MobileNetV2). 
`X = np.array([preprocess_input(self.load_img(img)) for img in imgs])`
I am able to run the test_MyTrain.py and train properly. But when i import as custom asset and train in IVI, the training is not working. May i know what i did wrong? 

Thanks in advance and have a nice day.

**Comment by MaximeDeloche** [comment]
Hi @enjoykcc456 ,

That fix works fine (unless all your images are in grayscale, in that case it would be better to update the model to use single-channel images, that way you wouldn't triple the image size with no additional info in it ; but that'll work fine).

Regarding your questions:
1. Tensorflow version is 1.14.0
2. option a), the full network is finetuned
3. What libraries do you use in your `preprocess_input` function? One option might be that a lib is available in your testing environment but not in the container of IVI (in that case you would have to include the library source code in your zip file - that works). It would be of great help to access the logs of that container ; we reported the need of showing logs in the interface but in the mean time the only option is to run "docker logs ..." on that container if you can access it.

If not, we might help. We're a team of technical pre-sales based in Montpellier, France and we provide support and/or remote access to IVI depending on projects. If you're interested drop me a private message on [LinkedIn](https://www.linkedin.com/in/maximedeloche) or [Twitter](https://twitter.com/maximedeloche) to discuss possibilities privately.

Have a nice day,

**Comment by enjoykcc456** [comment]
Hi @MaximeDeloche ,

I am using `from tensorflow.keras.applications.mobilenet_v2 import preprocess_input` for an imagenet pre-trained MobileNetV2. 

By access the log, i got the error `TypeError: ufunc 'true_divide' output (typecode 'd') could not be coerced to provided output parameter (typecode 'B') according to the casting rule ''same_kind''` as the function requires float array as input. 

Hence, i did the following and is now able to train.
```
X = np.array([self.load_img(img).astype(np.float32) for img in imgs])
X = preprocess_input(X)
```
I have sent you a linkedIn request under name of Gordon Kong. 

Thanks and have a nice day.

**Comment by MaximeDeloche** [comment]
Good to know it works! You're welcome.
Marking as closed, feel free to re-open if you need additional help.

Have a nice day,
